### ISSUE TITLE
Execução interrompida sem mensagem de erro

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/image-processing-service#4]
A última versão do script está quebrada. Executei o seguinte comando dentro na máquina, seguindo as instruções do README.md:

    python scripts/Application.py samples/06.4SEM.CENC.INTRA.SONY.jpg

O resultado foi:

```
Using TensorFlow backend.
Loading weights from /model/model_frcnn.hdf5
2018-01-03 11:19:25.399950: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-03 11:19:25.400013: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-03 11:19:25.400071: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-01-03 11:19:25.400205: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-03 11:19:25.400254: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Process started
Blur rate: 41.7165365242
Brightness rate: 140
[['palette' '1.0']
 ['circle' '1.0']]
Detecting circle...

Shadow rate: 0.003950663300245973
Performing segmentation...
Performing border detection...
Lenght analysis: 6 eggs.
Lenght analysis: 8 clusters.
Performing shape detection...

/opt/conda/lib/python3.6/site-packages/sklearn/utils/validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
Shape analysis: 6.
Shape analysis: 5.

Performing color detection...
Color - Eggs: 5
Color - Clusters: 0
{"eggCount": "5", "resolution": "1728x3072", "ipsVersion": "1.0"}
root@f4d042cc8461:/src# exit
exit
mba:ips vgeorge$ docker exec -i -t ips_server_1 /bin/bash
root@f4d042cc8461:/src# python scripts/Application.py samples/06.4SEM.CENC.INTRA.SONY.jpg 
Using TensorFlow backend.
Loading weights from /model/model_frcnn.hdf5
2018-01-03 11:25:22.988200: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-03 11:25:22.988378: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-03 11:25:22.988418: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-01-03 11:25:22.988505: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-01-03 11:25:22.988536: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Process started
Traceback (most recent call last):
  File "scripts/Application.py", line 35, in <module>
    if Defects.isBlurred(im) < 11.0:
  File "/src/scripts/Defects.py", line 16, in isBlurred
    cbimage = feature.canny(cv2.cvtColor(im, cv2.COLOR_BGR2GRAY), sigma=3)
NameError: name 'feature' is not defined
```
O problema foi introduzido após o commit ae8ce8fbbebdcc05c4188dc58310ab6b9430c71c.

@joaoherrera não temos testar a última versão do algoritmo até que o problema seja resolvido. Antes de comitar, teste a execução com o container Docker conforme as instruções do README. No futuro temos que ter uma suíte de testes para garantir a integridade do código neste repositório.

**Comment by joaoherrera** [comment]
@vgeorge Não consegui testar pois estava usando a máquina da lan house, uma vez que a internet aqui das Filipinas é precária. Após o tufão que passou pela região onde estou cheguei a tentar abrir a agenda mas ela não estava funcionando. Agora mudando para a porta 3131 voltou a abrir. Entretanto ainda recebo o seguinte erro: "process image job: missing 'image.url'". A chamada é realizada com o mesmo source do README.

**Comment by joaoherrera** [comment]
Problema corrigido e testado

**Comment by vgeorge** [comment]
Enviei uma imagem ruim (em anexo) e o script está sendo interrompido sem retornar mensagem de erro válida:

```
root@f4d042cc8461:/src# python /src/scripts/Application.py /images/5a77fd1a2431dd00b21cc1c1
Using TensorFlow backend.
Loading weights from /model/model_frcnn.hdf5
2018-02-05 06:52:15.654149: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-05 06:52:15.654219: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-05 06:52:15.654245: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2018-02-05 06:52:15.654256: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2018-02-05 06:52:15.654267: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Process started
Traceback (most recent call last):
  File "/src/scripts/Application.py", line 26, in <module>
    im = Utils.adjust_resolution(im)
  File "/src/scripts/Utils.py", line 61, in adjust_resolution
    IO.json_packing_error('ERR_008')
NameError: name 'IO' is not defined
```

![5a77fd1a2431dd00b21cc1c1](https://user-images.githubusercontent.com/329694/35806735-74bc31b8-0a78-11e8-8166-065868c3e5c7.png)

**Comment by joaoherrera** [comment]
Problema corrigido e testado.
